# Py Torch Tutorial

## Author: Chirag Bansal
### Date: 2024-07-30
* Description: This ipynb script demonstrates the use of PyTorch functions before diving deep into the Nural Network and CNN's using Pytorch. All these function are basic and we used them in numpy. But here I am explain how to use them in Pytorch tensors. In this file you come to know about how to initialize the tensors, `Type conversion`, `Math Functions`, `Some Comparision Functions`, `Reshaping ` and `Indexing` of Tensors.

In [2]:
import torch

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [4]:
# Creating my own tensor
my_tensor = torch.tensor([[1,2,3,4],[5,6,7,8]],dtype=torch.float16,device=device)

In [5]:
print(my_tensor)

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]], device='cuda:0', dtype=torch.float16)


In [6]:
print(my_tensor.dtype)

torch.float16


In [7]:
print(my_tensor.device)

cuda:0


In [8]:
print(my_tensor.shape)

torch.Size([2, 4])


### Other comman initialization methods

In [9]:
# If we don't know the values but want to initialize a tensor
# we can use `.empty function`
# This will create a tensor of given shape with whatever available in the memory randomly
x = torch.empty(size=(3,3))

In [10]:
print(x)

tensor([[-1.5378e-05,  8.3237e-43,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [11]:
x_zero = torch.zeros((3,3))

print(x_zero)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [12]:
# create an random tensor with values in between 0 and 1
x_rand = torch.rand((3,3))
print(x_rand)

tensor([[0.9319, 0.5108, 0.7916],
        [0.3704, 0.2960, 0.2342],
        [0.0439, 0.7160, 0.3520]])


In [13]:
x_ones = torch.ones((3,3))
print(x_ones)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [14]:
# `.eye function` creates an identity matrix (one's on diagonal and zeros on the rest of places of matrix)
x_eye = torch.eye(5,5)
print(x_eye)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [15]:
# work same as random but we have to provide a starting and ending (not included) and the steps how many steps you want at a time
x_arange = torch.arange(start=0,end=5,step=1)
print(x_arange)

tensor([0, 1, 2, 3, 4])


In [16]:
# Linespace, it will crate an tensor from starting to end including and in this `steps` means 
# how many values we need in between start and end value
x_linespace = torch.linspace(start=0.1,end=1,steps=10)
print(x_linespace)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [17]:
# create an tensor with normal distribution at mean 0 and std = 1
x = torch.empty(size=(1,3)).normal_(mean=0,std=1)
print(x)

# create an tensor with uniform distribution at mean 0 and std = 1
x = torch.empty(size=(1,3)).uniform_(0,1)
print(x)


tensor([[1.2538, 0.2702, 0.0304]])
tensor([[0.5387, 0.0891, 0.8837]])


In [18]:
# .diag create a diagonal matrix of one on diagonal
x_diag = torch.diag(torch.ones(3))

print(x_diag)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


### How to convert and initialize tensors to other types (int,float,double)

In [19]:
tensor = torch.arange(4)
print(tensor)

tensor([0, 1, 2, 3])


In [20]:
# Convert it to bool values
print(tensor.bool())

tensor([False,  True,  True,  True])


In [21]:
#  int 16
print(tensor.short())

tensor([0, 1, 2, 3], dtype=torch.int16)


In [22]:
#  int 64  (Important)
print(tensor.long())

tensor([0, 1, 2, 3])


In [23]:
#  float 16
print(tensor.half())

tensor([0., 1., 2., 3.], dtype=torch.float16)


In [24]:
#  float 32 (Important)
print(tensor.float())

tensor([0., 1., 2., 3.])


In [25]:
#  float 64
print(tensor.double())

tensor([0., 1., 2., 3.], dtype=torch.float64)


In [26]:
# Array to Tensor Conversion and vice-versa
import numpy as np
np_array = np.zeros((5,5))
print(np_array)

# Convert NP Array to a Tensor
print("\n NP to Tensor")
tensor = torch.from_numpy(np_array)
print(tensor)

# Convert Tensor to NP Array
print("\n Tensor to NP")
np_array_back = tensor.numpy()
print(np_array_back)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

 NP to Tensor
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

 Tensor to NP
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Tensor Math and Comparison Operations

In [27]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

# Addition
z1 = torch.empty(3)
torch.add(x,y,out=z1)
print(z1)

tensor([10., 10., 10.])


In [28]:
# Another addition method
z2 = torch.add(x,y)
print(z2)

# Third way
z = x+y
print(z)

tensor([10, 10, 10])
tensor([10, 10, 10])


In [29]:
# Subtraction
z = x-y
print(z)

tensor([-8, -6, -4])


In [30]:
# Division
z = torch.true_divide(x,y) # Element wise division if there are of equal shape
print(z)

tensor([0.1111, 0.2500, 0.4286])


In [31]:
# inplace operations

t = torch.zeros(3)

t.add_(x) # This will add x to t and store the result in t with duplicating it just mutate it 
print(t)

# Another method - `t+=x` it also to inplace operation

'''t+=x'''

# these are more time efficent

tensor([1., 2., 3.])


't+=x'

### Any function with `_` in pytorch means it's an inplace operation function 

In [32]:
# Exponentiation

z = x.pow(2) 
print(z)

# Another way to do this
z = x**2

tensor([1, 4, 9])


In [33]:
# Simple Comparision

z = x > 0
print(z)

z = x<0
print(z)

tensor([True, True, True])
tensor([False, False, False])


In [34]:
# Matrix Multiplication

x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
print(x1.shape, x2.shape)

x3 = torch.mm(x1,x2) # 2x3
print(x3)

# Another way to do this (Easy way)
x3 = x1.mm(x2)

torch.Size([2, 5]) torch.Size([5, 3])
tensor([[1.7114, 1.5789, 1.2250],
        [1.2920, 0.9480, 0.5619]])


In [35]:
# Matrix Exponentiation

matrix_exp = torch.rand(5,5)
print(matrix_exp.matrix_power(3))

tensor([[5.0797, 2.9595, 3.5727, 4.6210, 3.3360],
        [3.6838, 2.0340, 2.6809, 3.0932, 2.3306],
        [3.9513, 2.2440, 2.9045, 3.8010, 2.8852],
        [2.7453, 1.3947, 2.1073, 2.5086, 2.1312],
        [3.1881, 1.6408, 2.4369, 3.1864, 2.7149]])


In [36]:
# Element wise multiplication
z = x * y
print(z)
# print(matrix_exp.mul(matrix_exp))

tensor([ 9, 16, 21])


In [37]:
# dot product

z = torch.dot(x,y)
print(z)

tensor(46)


In [38]:
# Batch Matrix Multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch,n,m))
tensor2 = torch.rand((batch,m,p))

out_bmm = torch.bmm(tensor1,tensor2) # (batch,n,b)

print(out_bmm)
# print(tensor1)
# print(tensor2)

tensor([[[4.3864, 4.5019, 4.3879,  ..., 3.7000, 3.2567, 4.8732],
         [7.2369, 6.8138, 5.9412,  ..., 6.2538, 5.5567, 6.8641],
         [8.2836, 6.7560, 5.8781,  ..., 7.0580, 6.3247, 7.2988],
         ...,
         [6.1221, 4.9229, 4.7770,  ..., 6.1097, 5.1617, 6.0959],
         [6.7976, 5.4679, 4.4277,  ..., 5.1875, 4.3848, 6.3197],
         [6.6375, 5.5982, 4.6443,  ..., 5.5355, 5.1217, 6.1381]],

        [[6.2433, 4.8275, 6.0579,  ..., 4.3919, 4.7032, 5.5916],
         [7.2219, 5.2161, 6.8154,  ..., 6.0896, 5.5787, 7.2308],
         [5.9265, 5.1475, 5.8021,  ..., 4.4458, 5.1117, 5.8060],
         ...,
         [6.4258, 4.6736, 6.0116,  ..., 4.5359, 5.0324, 5.9789],
         [5.3812, 3.6581, 5.1210,  ..., 4.4235, 4.3529, 5.4115],
         [5.8829, 4.1431, 5.4690,  ..., 4.9544, 4.6483, 5.8155]],

        [[3.8820, 4.9864, 4.3089,  ..., 3.9572, 3.2397, 3.6117],
         [4.0674, 5.3987, 3.9115,  ..., 4.2193, 3.3822, 3.7193],
         [5.0277, 6.0586, 4.7439,  ..., 5.6518, 4.7461, 4.

In [42]:
# Example of Broadcasting

x1 = torch.rand((5,5))
x2 = torch.rand((1,5))

z = x1 - x2

print(z)

z = x1**x2
print(z)

# Other useful tensor operations
sum_x = torch.sum(x,dim=0)
# x.sum(dim=0)
print(sum_x)

tensor([[-0.5530,  0.2941, -0.0991,  0.1854,  0.2195],
        [-0.5563, -0.0320,  0.0566,  0.2900, -0.6785],
        [-0.6830, -0.0687,  0.2747,  0.4439, -0.1207],
        [-0.6188,  0.0764,  0.5775,  0.8966, -0.3161],
        [ 0.0386,  0.4428, -0.1076,  0.2749, -0.4415]])
tensor([[0.3044, 0.8567, 0.6164, 0.8870, 0.9521],
        [0.3007, 0.6699, 0.7305, 0.9139, 0.0922],
        [0.1462, 0.6417, 0.8472, 0.9433, 0.6888],
        [0.2286, 0.7423, 0.9697, 0.9991, 0.5179],
        [0.8451, 0.9205, 0.6089, 0.9104, 0.3953]])
tensor(6)


In [43]:
values, indices = torch.max(x,dim = 0) # x.max(dim=0)
print(values,indices)

tensor(3) tensor(2)


In [44]:
values, indices = torch.min(x,dim = 0)  # x.min(dim=0)
print(values,indices)

tensor(1) tensor(0)


In [45]:
abs_x = torch.abs(x) # x.abs(dim=0)
print(abs_x)

tensor([1, 2, 3])


In [46]:
z = torch.argmax(x,dim = 0) # Return the index of maximum values of tensor
# x.agemax(dim=0)
print(z)

tensor(2)


In [47]:
z = torch.argmin(x,dim = 0) # Return the index of minimum values of tensor
# x.agrmin(dim=0)
print(z)

tensor(0)


In [49]:
# Mean
# It take only float values, So converting the tensor into float
mean_x = torch.mean(x.float(),dim=0)
print(mean_x)

tensor(2.)


In [51]:
# For Elementwise Comparision of two tensors

z = torch.eq(x,y)
# If elements are equal print true else false
print(z)

tensor([False, False, False])


In [52]:
# Sort
sorted_y, indices = torch.sort(y,dim=0,descending=False)  # Specify the dimention to be sorted
print(sorted_y,indices)

tensor([7, 8, 9]) tensor([2, 1, 0])


In [55]:
#`torch.clamp, what it do is, for tensor x if any value is less than 0 it will clamped to (changed to 0) and if any value greater than "specific value" will clamped to that value (changed to specific value)`
# `torch.clamp` is used to limit the range of a tensor or scalar.
# It's optional to add both min and max we can use any one also
print(y)
z = torch.clamp(y,min = 0, max=8)
print(z)

tensor([9, 8, 7])
tensor([8, 8, 7])


In [56]:
x = torch.tensor([1,0,1,1,1],dtype=torch.bool)
z = torch.any(x)  # it means at least one value must be true then it will return true
print(z)
z = torch.all(x) # it means all values must be true only then it will retun true
print(z)

tensor(True)
tensor(False)


## Tensor Indexing

In [58]:
batch_size = 10
features = 25
x = torch.rand((batch_size,features))

print(x[0].shape) #x[0,:]
print(x[:,0].shape)

torch.Size([25])
torch.Size([10])


In [60]:
# First 10 featuers
print(x[2,:10])

tensor([0.6948, 0.8055, 0.2960, 0.0974, 0.3341, 0.7782, 0.0993, 0.2851, 0.3746,
        0.3653])


In [66]:
# Fancy Indexing
y = torch.arange(10)
indices = [2,5,8]  # INDEX NUMBERS
print(y)
print(y[indices])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([2, 5, 8])


In [68]:
y = torch.rand((3,5))
print(y)
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
# Element 1 = y[1,4] 
# Element 2 = y[0,0] 
print(y[rows,cols])

tensor([[0.6641, 0.0855, 0.8434, 0.3149, 0.8187],
        [0.0254, 0.3695, 0.5580, 0.3728, 0.8185],
        [0.6116, 0.6950, 0.3206, 0.8489, 0.3557]])
tensor([0.8185, 0.6641])


## More Advance Indexing

In [70]:
x = torch.arange(10)

print(x[(x<2) | (x>8)]) # it will pick out all the elements that are greater than 8 or less than 2
print(x[(x<2) & (x>8)]) # it will pick out all the elements that are greater than 8 and less than 2

tensor([0, 1, 9])
tensor([], dtype=torch.int64)


In [71]:
print(x[x.remainder(2)==0]) # if the remainder of x modules 2 equals to 2 then it will be printed

tensor([0, 2, 4, 6, 8])


In [75]:
# Useful operators
print(torch.where(x>5,x,x*2)) # if x>5 then x else x*2 
print(torch.tensor([1,1,2,3,4,4,5,6]).unique())
print(x.ndimension()) # check how many dimensions of x we have (eg - 5x5x5 - answer will be 3)
print(x.numel()) # check how many elements are there in x



tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([1, 2, 3, 4, 5, 6])
1
10


## Tensor Reshaping

In [78]:
x = torch.arange(9)
x_3x3 = x.view(3,3)  # to make x a 3x3 matrix. it  can only operate on contiguous tensor.   
# Contiguous array is just an array stored in an unbroken block of memory: to access the next value in the array, we just move to the next memory address.
print(x_3x3)
print(x_3x3.shape)

# Another method
x_3x3 = x.reshape(3,3)  # to make x a 3x3 matrix. reshape() can operate on both contiguous and non-contiguous tensor
print(x_3x3)


tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
torch.Size([3, 3])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [81]:
y = x_3x3.t()  # [0,3,6,1,4,7,2,5,8] so to transpose it for each element in original memory block we have to jump 3 time which makes it non-contiguous. So, if we want 
# to transpose it we have to make it contiguous first or we have to use `.reshape function` `.view will not work here it will give an error`
print(y)

print(y.view(9))

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])


RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [83]:
# make it contiguous first
print(y.contiguous().view(9))

# Another method use of reshape
print(y.reshape(9))

tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [84]:
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))

print(torch.cat((x1,x2),dim=0).shape) # Concatenate along rows , dim = 0 to specify them to concat via rows for colum dim = 1
print(torch.cat((x1,x2),dim=0)) # Concatenate along rows

torch.Size([4, 5])
tensor([[0.6327, 0.2510, 0.9173, 0.1595, 0.7213],
        [0.0517, 0.3009, 0.3062, 0.5540, 0.6386],
        [0.5793, 0.9437, 0.8811, 0.0249, 0.7432],
        [0.7536, 0.4411, 0.7437, 0.2118, 0.8691]])


In [85]:
print(torch.cat((x1,x2),dim=1).shape) # Concatenate along col , dim = 0 to specify them to concat via rows for colum dim = 1
print(torch.cat((x1,x2),dim=1)) # Concatenate along col

torch.Size([2, 10])
tensor([[0.6327, 0.2510, 0.9173, 0.1595, 0.7213, 0.5793, 0.9437, 0.8811, 0.0249,
         0.7432],
        [0.0517, 0.3009, 0.3062, 0.5540, 0.6386, 0.7536, 0.4411, 0.7437, 0.2118,
         0.8691]])


In [86]:
z = x1.view(-1)  # To make a 1 x n dimension vector 
print(z)

tensor([0.6327, 0.2510, 0.9173, 0.1595, 0.7213, 0.0517, 0.3009, 0.3062, 0.5540,
        0.6386])


In [87]:
batch = 64
x = torch.rand((batch,2,5))
z = x.view(batch,-1) # it will make a 64 x 10 matrix
print(z.shape)

torch.Size([64, 10])


In [88]:
z = x.permute(0,2,1) # .permute is use to change the dimensions in this case we want 0 at 0 , 2 at 1 and 1 at 2
print(z.shape)
print(z)

torch.Size([64, 5, 2])
tensor([[[7.9770e-01, 1.7148e-01],
         [5.9173e-01, 2.4289e-01],
         [8.7804e-01, 7.7173e-01],
         [8.9818e-01, 5.1646e-01],
         [5.9191e-01, 6.6103e-01]],

        [[1.6596e-01, 9.4913e-01],
         [7.6349e-01, 8.0573e-01],
         [5.0185e-01, 9.2574e-01],
         [2.1424e-01, 3.4575e-02],
         [3.7140e-01, 7.1423e-01]],

        [[2.5194e-01, 3.3003e-01],
         [2.0786e-01, 1.6912e-02],
         [8.2335e-01, 3.0759e-01],
         [5.3408e-01, 6.4306e-01],
         [5.5629e-01, 3.7648e-01]],

        [[3.0414e-01, 8.1636e-01],
         [6.7368e-01, 3.2340e-01],
         [3.3260e-02, 6.4935e-01],
         [2.9386e-01, 3.5702e-01],
         [1.9550e-01, 8.4384e-01]],

        [[2.2406e-01, 2.0355e-01],
         [7.7794e-01, 5.0716e-01],
         [8.9083e-01, 7.8835e-01],
         [4.8685e-01, 9.2288e-02],
         [6.4902e-01, 8.8415e-01]],

        [[8.7035e-01, 6.9500e-01],
         [1.9605e-01, 7.2939e-01],
         [1.8356e-01, 

In [90]:
x = torch.arange(10) # [10]
print(x.unsqueeze(0).shape) # it will add a dimension at 0 index [1,10]
print(x.unsqueeze(0))
print("\n")
print(x.unsqueeze(1).shape) # it will add a dimension at 1 index [10,1]
print(x.unsqueeze(1))


torch.Size([1, 10])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])


torch.Size([10, 1])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


In [92]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1) # 1X1X10
print(x)
print(x.shape)

z = x.squeeze(1) # it will remove the dimension at 1 index
print(z.shape)
print(z)

tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])
torch.Size([1, 1, 10])
torch.Size([1, 10])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
